# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_earned',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='caps',
        ),
        migrations.AlterField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='commission_total',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='commissions',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='user',
            name='datascientist_reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='noteworthy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='redeem_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='remember_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_purchase',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='trend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
