# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuray', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('test_points', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('train_points', models.DecimalField(decimal_places=5, default=0, max_digits=18)),
                ('bias', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('variance', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(max_length=255)),
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('algo_metadata', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AlgoMetaData')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commissions', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('commisssion_accrued', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('product_sales', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessparameters', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('datatype', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_datafield', to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('accessparameters', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('datafields', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_dataset', to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.IntegerField(blank=True, null=True)),
                ('foreign_type', models.IntegerField(choices=[(0, 'ensemble'), (1, 'solution')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(-1, 'requested'), (0, 'complete'), (1, 'none')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ensembles_dataset', to='api.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MetaEnsemble',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('collection_id', models.IntegerField()),
                ('foreign_id', models.IntegerField()),
                ('foreign_type', models.IntegerField(choices=[(0, 'ensemble'), (1, 'solution')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(-1, 'requested'), (0, 'complete'), (1, 'none')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metaensembles_dataset', to='api.DataSet')),
                ('ensemble', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metaensembles_ensemble', to='api.Ensemble')),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jupyternotebook_ID', models.IntegerField(default=0)),
                ('graphdatabase_ID', models.IntegerField(default=0)),
                ('accessparameters', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('datasource', models.CharField(max_length=255)),
                ('datafields', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('ensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_ensemble', to='api.Ensemble')),
                ('metaensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_metaensemble', to='api.MetaEnsemble')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Notebook')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.BinaryField(blank=True, null=True)),
                ('ABTest', models.IntegerField(default=1)),
                ('PredictionAccuracyScore', models.IntegerField(default=0)),
                ('ChangefromPrevious', models.IntegerField(default=0)),
                ('PredictedImpact', models.IntegerField(default=0)),
                ('RecordsinFile', models.IntegerField(default=0)),
                ('DateRun', models.DateTimeField(blank=True, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logfile', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('datafield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_datafield', to='api.DataField')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_dataset', to='api.DataSet')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_notebook', to='api.Notebook')),
            ],
        ),
        migrations.CreateModel(
            name='recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DataSet')),
                ('ensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ensemble')),
                ('metaensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MetaEnsemble')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('rating', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(-1, 'requested'), (1, 'complete')], default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('timed', models.BooleanField(default=False)),
                ('starting_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('ending_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('Category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_solution', to='api.Author')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions_dataset', to='api.DataSet')),
                ('ensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ensemble')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Library')),
                ('metaensemble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MetaEnsemble')),
                ('notebook', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions_notebook', to='api.Notebook')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Solution')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions_price', to='api.Price')),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.SolutionType')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_solution', to='api.User')),
                ('usergroup_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='recommendations',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Solution'),
        ),
        migrations.AddField(
            model_name='price',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_solution', to='api.Solution'),
        ),
        migrations.AddField(
            model_name='price',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='performance',
            name='PerformanceResult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.PerformanceResult'),
        ),
        migrations.AddField(
            model_name='performance',
            name='ensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances_ensemble', to='api.Ensemble'),
        ),
        migrations.AddField(
            model_name='performance',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances_notebook', to='api.Notebook'),
        ),
        migrations.AddField(
            model_name='performance',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Solution'),
        ),
        migrations.AddField(
            model_name='performance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='performance',
            name='usergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_performance', to='api.Performance'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_price', to='api.Price'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_solution', to='api.Solution'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='type',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.NotebookType'),
        ),
        migrations.AddField(
            model_name='metaensemble',
            name='notebook',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metaensembles_notebook', to='api.Notebook'),
        ),
        migrations.AddField(
            model_name='library',
            name='vertical',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Vertical'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ensembles_notebook', to='api.Notebook'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ensemble'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='performance',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ensembles_performance', to='api.Performance'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='usergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_ensemble', to='api.Ensemble'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='metaensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_metaensemble', to='api.MetaEnsemble'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DataSet'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_price', to='api.Price'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_solution', to='api.Solution'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dataset', to='api.User'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='dataset',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DataSet'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_datafield', to='api.Price'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Solution'),
        ),
        migrations.AddField(
            model_name='datafield',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_datafields', to='api.User'),
        ),
        migrations.AddField(
            model_name='commission',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Solution'),
        ),
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions_user', to='api.User'),
        ),
        migrations.AddField(
            model_name='category',
            name='vertical',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Vertical'),
        ),
    ]
