# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-13 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_solutionnavigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_category', to='api.Category')),
                ('category_parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('dataset', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.DataSet')),
                ('ensemble', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Ensemble')),
                ('library', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Library')),
                ('metaensemble', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.MetaEnsemble')),
                ('notebook', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_notebook', to='api.Notebook')),
                ('notebook_parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Notebook')),
                ('performance', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Performance')),
                ('solution', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_solution', to='api.Solution')),
                ('solution_parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Solution')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='vertical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vertical',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vertical_user', to='api.User'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='usergroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='vertical',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Vertical'),
        ),
    ]
