# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170613_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsrecord',
            name='category_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='notebook_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='notebook_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='performance_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='solution_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='usergroup_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='vertical_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
