# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-14 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170613_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='category_parent',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='ensemble',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='library',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='metaensemble',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='notebook_description',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='notebook_name',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='notebook_parent',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='performance_name',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='solution_name',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='solution_parent',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='usergroup',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='usergroup_name',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='vertical',
        ),
        migrations.RemoveField(
            model_name='analyticsrecord',
            name='vertical_name',
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='user',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
