# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170614_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsrecord',
            name='category',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_category', to='api.Category'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='category_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='category_parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='dataset',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DataSet'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='ensemble',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ensemble'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='library',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Library'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='metaensemble',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MetaEnsemble'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='notebook',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_notebook', to='api.Notebook'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='notebook_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='notebook_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='notebook_parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Notebook'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='performance',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Performance'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='performance_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='solution',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_solution', to='api.Solution'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='solution_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='solution_parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Solution'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='usergroup',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='usergroup_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='vertical',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Vertical'),
        ),
        migrations.AddField(
            model_name='analyticsrecord',
            name='vertical_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
