# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170614_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsrecord',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_category', to='api.Category'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='category_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='dataset',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DataSet'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='ensemble',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ensemble'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='library',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Library'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='metaensemble',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MetaEnsemble'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='notebook',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_notebook', to='api.Notebook'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='notebook_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Notebook'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='performance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Performance'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='solution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_solution', to='api.Solution'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='solution_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Solution'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='usergroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup'),
        ),
        migrations.AlterField(
            model_name='analyticsrecord',
            name='vertical',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Vertical'),
        ),
    ]
