export const FLAG_TOGGLE 				= 'FLAG_TOGGLE';
export const GET_SOLUTION_BUY_USER 		= 'GET_SOLUTION_BUY_USER';
export const GET_SOLUTION_BY_CATEGORY 	= 'GET_SOLUTION_BUY_CATEGORY';
export const GET_CATEGORIES 			= 'GET_CATEGORIES';
export const GET_SOLUTION_PARENT_ID		= 'GET_SOLUTION_PARENT_ID';
export const SET_SOLUTION_PARENT_ID		= 'SET_SOLUTION_PARENT_ID';
export const GET_SOLUTION_BY_PARENT_ID 	= 'GET_SOLUTION_BY_PARENT_ID';

