# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaensemble',
            name='notebook',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metaensembles_notebook', to='solutions.Notebook'),
        ),
    ]
