# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='graphdatabase_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='jupyternotebook_ID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Notebook'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='ensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Ensemble'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='metaensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.MetaEnsemble'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solutionparent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution'),
        ),
    ]
