# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='library_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
