# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-10 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='PerformanceResults',
            new_name='PerformanceResult',
        ),
        migrations.AlterField(
            model_name='performance',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
