# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='performance',
            field=models.ManyToManyField(to='solutions.Performance'),
        ),
    ]
