# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebook_dataset', to='solutions.DataSet'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_ensemble', to='solutions.Ensemble'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='metaensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_metaensemble', to='solutions.MetaEnsemble'),
        ),
    ]
