# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dataset', to='api.User'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='library_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solutionparent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='usergroup_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserGroup'),
        ),
    ]
