# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_vertical_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertical',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
    ]
