# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('solutions', '0002_auto_20170506_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessparameters', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('datafields', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
                ('price', models.ManyToManyField(to='solutions.Price')),
            ],
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='performance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='solutions.Performance'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solutionparent',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Type'),
        ),
    ]
