# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170509_0732'),
        ('solutions', '0002_auto_20170508_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_solution', to='solutions.Solution'),
        ),
        migrations.AddField(
            model_name='performance',
            name='Notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances_notebook', to='solutions.Notebook'),
        ),
        migrations.AddField(
            model_name='price',
            name='datafield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_datafield', to='solutions.DataField'),
        ),
        migrations.AddField(
            model_name='price',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_dataset', to='solutions.DataSet'),
        ),
        migrations.AddField(
            model_name='price',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_notebook', to='solutions.Notebook'),
        ),
        migrations.AddField(
            model_name='price',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_solution', to='solutions.Solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='notebook',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions_notebook', to='solutions.Notebook'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='dataset',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.DataSet'),
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='price',
        ),
        migrations.AddField(
            model_name='datafield',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices_datafield', to='solutions.Price'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_datafields', to='api.User'),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='price',
        ),
        migrations.AddField(
            model_name='dataset',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets_price', to='solutions.Price'),
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='author',
        ),
        migrations.AddField(
            model_name='notebook',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Notebook'),
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='performance',
        ),
        migrations.AddField(
            model_name='notebook',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_performance', to='solutions.Performance'),
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='price',
        ),
        migrations.AddField(
            model_name='notebook',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_price', to='solutions.Price'),
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='solution',
        ),
        migrations.AddField(
            model_name='notebook',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_solution', to='solutions.Solution'),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='dataset',
        ),
        migrations.AddField(
            model_name='solution',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions_dataset', to='solutions.DataSet'),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='price',
        ),
        migrations.AddField(
            model_name='solution',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions_price', to='solutions.Price'),
        ),
    ]
