# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_metaensemble_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ensembles_notebook', to='solutions.Notebook'),
        ),
    ]
