# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20170509_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='ChangefromPrevious',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='DateRun',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='PredictedImpact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='PredictionAccuracyScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='RecordsinFile',
            field=models.IntegerField(default=0),
        ),
    ]
