# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-13 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_ensemble_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemble',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ensembles_dataset', to='solutions.DataSet'),
        ),
        migrations.AddField(
            model_name='metaensemble',
            name='dataset',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metaensembles_dataset', to='solutions.DataSet'),
        ),
    ]
