# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_auto_20170509_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='solutionparent',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='ensemble',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.Ensemble'),
        ),
    ]
